name: IIS-workfloe
on:
  push:
    branches: [master]
  workflow_dispatch:   
env:
  SLN_FILE: PartsUnlimited.sln
  IIS_SITE_PATH: C:\pulwebsite
  IIS_POOL: pulweb
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 
jobs:
  build:
    name: BUILD USING VS2019
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2.2.0
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v1.0.2
      - name: Setup MSbuild
        uses: microsoft/setup-msbuild@v1
      - name: NuGet restore
        run: nuget restore
      - name: BuildApp
        run: |
          msbuild ${{env.SLN_FILE}} /p:TransformWebConfigEnabled=False /p:AutoParameterizationWebConfigConnectionStrings=False /p:Configuration=Release /p:Platform='Any CPU' /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="${{github.workspace}}\stagingdir"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}\stagingdir

  deploy:
    name: DEPLOY TO IIS
    runs-on: [self-hosted,iis]
    needs: [build]
    defaults:
      run: 
        shell: powershell
    env:
      PACKAGE_TEMP_PATH: Content/D_C/a/PartsUnlimited/PartsUnlimited/src/PartsUnlimitedWebsite/obj/Release/Package/PackageTmp
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: drop
          path: ${{github.workspace}}
  
      - name: Extract Artifact
        run: expand-archive -path '*.zip' -destinationpath '.\webapp' -force

      - name: Replace tokens
        uses: cschleiden/replace-tokens@v1.1
        with:
          files: '["./webapp/${{env.PACKAGE_TEMP_PATH}}/Web.config"]'
        env:
          SQL_CONNECTION_STRING: ${{secrets.SQLCONNECTIONSTRING}}
        
      - run: Remove-Item ./** -Recurse
        working-directory: ${{env.IIS_SITE_PATH}}
        name: Clear IIS path
      
      - run: Copy-Item ./webapp/${{env.PACKAGE_TEMP_PATH}} -Destination ${{env.IIS_SITE_PATH}} -Recurse
        name: Copy to IIS path
      
      - run: |
          Import-Module WebAdministration
          Stop-WebSite ${{env.IIS_WEBSITE}}
          Start-WebSite ${{env.IIS_WEBSITE}}
        name: Restart IIS site
